
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Entry monitor2;

	private global::Gtk.Entry monitor;

	private global::Gtk.Table table;

	private global::Gtk.Button clear_click;

	private global::Gtk.Button divide_click;

	private global::Gtk.Button eight_click;

	private global::Gtk.Button five_click;

	private global::Gtk.Button four_click;

	private global::Gtk.Button minus_click;

	private global::Gtk.Button multiply_click;

	private global::Gtk.Button nine_click;

	private global::Gtk.Button one_click;

	private global::Gtk.Image peter_G;

	private global::Gtk.Button plus_click;

	private global::Gtk.Button point_click;

	private global::Gtk.Button result_click;

	private global::Gtk.Button seven_click;

	private global::Gtk.Button six_click;

	private global::Gtk.Button three_click;

	private global::Gtk.Button two_click;

	private global::Gtk.Button zero_click;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.monitor2 = new global::Gtk.Entry();
		this.monitor2.CanFocus = true;
		this.monitor2.Name = "monitor2";
		this.monitor2.IsEditable = true;
		this.monitor2.InvisibleChar = '•';
		this.vbox2.Add(this.monitor2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.monitor2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.monitor = new global::Gtk.Entry();
		this.monitor.HeightRequest = 120;
		this.monitor.CanFocus = true;
		this.monitor.Name = "monitor";
		this.monitor.IsEditable = true;
		this.monitor.InvisibleChar = '•';
		this.vbox2.Add(this.monitor);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.monitor]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table = new global::Gtk.Table(((uint)(5)), ((uint)(4)), false);
		this.table.Name = "table";
		this.table.RowSpacing = ((uint)(2));
		this.table.ColumnSpacing = ((uint)(2));
		// Container child table.Gtk.Table+TableChild
		this.clear_click = new global::Gtk.Button();
		global::Gtk.Tooltips w4 = new Gtk.Tooltips();
		w4.SetTip(this.clear_click, "clear", "clear");
		this.clear_click.CanFocus = true;
		this.clear_click.Name = "clear_click";
		this.clear_click.UseUnderline = true;
		this.clear_click.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.table.Add(this.clear_click);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table[this.clear_click]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.YPadding = ((uint)(3));
		// Container child table.Gtk.Table+TableChild
		this.divide_click = new global::Gtk.Button();
		w4.SetTip(this.divide_click, "divide", "divide");
		this.divide_click.CanFocus = true;
		this.divide_click.Name = "divide_click";
		this.divide_click.UseUnderline = true;
		this.divide_click.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table.Add(this.divide_click);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table[this.divide_click]));
		w6.LeftAttach = ((uint)(3));
		w6.RightAttach = ((uint)(4));
		w6.YPadding = ((uint)(3));
		// Container child table.Gtk.Table+TableChild
		this.eight_click = new global::Gtk.Button();
		this.eight_click.CanFocus = true;
		this.eight_click.Name = "eight_click";
		this.eight_click.UseUnderline = true;
		this.eight_click.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table.Add(this.eight_click);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table[this.eight_click]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		// Container child table.Gtk.Table+TableChild
		this.five_click = new global::Gtk.Button();
		this.five_click.CanFocus = true;
		this.five_click.Name = "five_click";
		this.five_click.UseUnderline = true;
		this.five_click.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table.Add(this.five_click);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table[this.five_click]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		// Container child table.Gtk.Table+TableChild
		this.four_click = new global::Gtk.Button();
		this.four_click.CanFocus = true;
		this.four_click.Name = "four_click";
		this.four_click.UseUnderline = true;
		this.four_click.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table.Add(this.four_click);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table[this.four_click]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		// Container child table.Gtk.Table+TableChild
		this.minus_click = new global::Gtk.Button();
		w4.SetTip(this.minus_click, "minus", "minus");
		this.minus_click.CanFocus = true;
		this.minus_click.Name = "minus_click";
		this.minus_click.UseUnderline = true;
		this.minus_click.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table.Add(this.minus_click);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table[this.minus_click]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(3));
		w10.RightAttach = ((uint)(4));
		// Container child table.Gtk.Table+TableChild
		this.multiply_click = new global::Gtk.Button();
		w4.SetTip(this.multiply_click, "multiply", "multiply");
		this.multiply_click.CanFocus = true;
		this.multiply_click.Name = "multiply_click";
		this.multiply_click.UseUnderline = true;
		this.multiply_click.Label = global::Mono.Unix.Catalog.GetString("*");
		this.table.Add(this.multiply_click);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table[this.multiply_click]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(3));
		w11.RightAttach = ((uint)(4));
		// Container child table.Gtk.Table+TableChild
		this.nine_click = new global::Gtk.Button();
		this.nine_click.CanFocus = true;
		this.nine_click.Name = "nine_click";
		this.nine_click.UseUnderline = true;
		this.nine_click.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table.Add(this.nine_click);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table[this.nine_click]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(2));
		w12.RightAttach = ((uint)(3));
		// Container child table.Gtk.Table+TableChild
		this.one_click = new global::Gtk.Button();
		this.one_click.CanFocus = true;
		this.one_click.Name = "one_click";
		this.one_click.UseUnderline = true;
		this.one_click.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table.Add(this.one_click);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table[this.one_click]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		// Container child table.Gtk.Table+TableChild
		this.peter_G = new global::Gtk.Image();
		w4.SetTip(this.peter_G, "Peter Griffin", "Peter Griffin");
		this.peter_G.Sensitive = false;
		this.peter_G.Name = "peter_G";
		this.peter_G.Xpad = 8;
		this.peter_G.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Peter_Griffin_Calculator.PeterGriffin3.png");
		this.table.Add(this.peter_G);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table[this.peter_G]));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(0));
		w14.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table.Gtk.Table+TableChild
		this.plus_click = new global::Gtk.Button();
		w4.SetTip(this.plus_click, "plus", "plus");
		this.plus_click.CanFocus = true;
		this.plus_click.Name = "plus_click";
		this.plus_click.UseUnderline = true;
		this.plus_click.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table.Add(this.plus_click);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table[this.plus_click]));
		w15.TopAttach = ((uint)(3));
		w15.BottomAttach = ((uint)(4));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		// Container child table.Gtk.Table+TableChild
		this.point_click = new global::Gtk.Button();
		w4.SetTip(this.point_click, "point", "point");
		this.point_click.CanFocus = true;
		this.point_click.Name = "point_click";
		this.point_click.UseUnderline = true;
		this.point_click.Label = global::Mono.Unix.Catalog.GetString(".");
		this.table.Add(this.point_click);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table[this.point_click]));
		w16.TopAttach = ((uint)(4));
		w16.BottomAttach = ((uint)(5));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(7));
		// Container child table.Gtk.Table+TableChild
		this.result_click = new global::Gtk.Button();
		w4.SetTip(this.result_click, "equal", "equal");
		this.result_click.CanFocus = true;
		this.result_click.Name = "result_click";
		this.result_click.UseUnderline = true;
		this.result_click.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table.Add(this.result_click);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table[this.result_click]));
		w17.TopAttach = ((uint)(4));
		w17.BottomAttach = ((uint)(5));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(4));
		// Container child table.Gtk.Table+TableChild
		this.seven_click = new global::Gtk.Button();
		this.seven_click.CanFocus = true;
		this.seven_click.Name = "seven_click";
		this.seven_click.UseUnderline = true;
		this.seven_click.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table.Add(this.seven_click);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table[this.seven_click]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		// Container child table.Gtk.Table+TableChild
		this.six_click = new global::Gtk.Button();
		this.six_click.CanFocus = true;
		this.six_click.Name = "six_click";
		this.six_click.UseUnderline = true;
		this.six_click.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table.Add(this.six_click);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table[this.six_click]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		// Container child table.Gtk.Table+TableChild
		this.three_click = new global::Gtk.Button();
		this.three_click.CanFocus = true;
		this.three_click.Name = "three_click";
		this.three_click.UseUnderline = true;
		this.three_click.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table.Add(this.three_click);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table[this.three_click]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.LeftAttach = ((uint)(2));
		w20.RightAttach = ((uint)(3));
		// Container child table.Gtk.Table+TableChild
		this.two_click = new global::Gtk.Button();
		this.two_click.CanFocus = true;
		this.two_click.Name = "two_click";
		this.two_click.UseUnderline = true;
		this.two_click.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table.Add(this.two_click);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table[this.two_click]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.LeftAttach = ((uint)(1));
		w21.RightAttach = ((uint)(2));
		// Container child table.Gtk.Table+TableChild
		this.zero_click = new global::Gtk.Button();
		this.zero_click.CanFocus = true;
		this.zero_click.Name = "zero_click";
		this.zero_click.UseUnderline = true;
		this.zero_click.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table.Add(this.zero_click);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table[this.zero_click]));
		w22.TopAttach = ((uint)(4));
		w22.BottomAttach = ((uint)(5));
		this.vbox1.Add(this.table);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table]));
		w23.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 334;
		this.DefaultHeight = 489;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.zero_click.Clicked += new global::System.EventHandler(this.OnZeroClickClicked);
		this.two_click.Clicked += new global::System.EventHandler(this.OnTwoClickClicked);
		this.three_click.Clicked += new global::System.EventHandler(this.OnThreeClickClicked);
		this.six_click.Clicked += new global::System.EventHandler(this.OnSixClickClicked);
		this.seven_click.Clicked += new global::System.EventHandler(this.OnSevenClickClicked);
		this.result_click.Clicked += new global::System.EventHandler(this.OnResultClickClicked);
		this.point_click.Clicked += new global::System.EventHandler(this.OnPointClickClicked);
		this.plus_click.Clicked += new global::System.EventHandler(this.OnPlusClickClicked);
		this.one_click.Clicked += new global::System.EventHandler(this.OnOneClickClicked);
		this.nine_click.Clicked += new global::System.EventHandler(this.OnNineClickClicked);
		this.multiply_click.Clicked += new global::System.EventHandler(this.OnMultiplyClickClicked);
		this.minus_click.Clicked += new global::System.EventHandler(this.OnMinusClickClicked);
		this.four_click.Clicked += new global::System.EventHandler(this.OnFourClickClicked);
		this.five_click.Clicked += new global::System.EventHandler(this.OnFiveClickClicked);
		this.eight_click.Clicked += new global::System.EventHandler(this.OnEightClickClicked);
		this.divide_click.Clicked += new global::System.EventHandler(this.OnDivideClickClicked);
		this.clear_click.Clicked += new global::System.EventHandler(this.OnClearClickClicked);
	}
}
